spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test

    username: sa
    password:
  sql:
    init:
      mode: always
      schema: classpath/schema.sql
      data: classpath/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true


